"""Agent Controller: deterministic state machine driving exchangeable AI workers."""

from agent_controller.capability import (
    DEFAULT_CAPABILITIES,
    WorkerCapability,
    capability_for,
    classify_worker_error,
    satisfies,
)
from agent_controller.cli_worker import AgyCliWorker, ClaudeCodeWorker, CodexCliWorker, GrokCliWorker
from agent_controller.complete import (
    CompleteBlocker,
    CompleteBlockerCode,
    CompleteCheckResult,
    CompleteGate,
    CompleteGateError,
)
from agent_controller.acceptance import ensure_todo_contracts, verify_contract, verify_contracts
from agent_controller.design import (
    default_design_stages,
    design_artifact_statuses,
    design_stages_for_task_type,
    invalidate_from,
    mark_fast_path_skips,
    run_design,
)
from agent_controller.document_stage import (
    STAGE_TRANSITIONS,
    DocumentStageConfig,
    next_phase,
    run_document_stage,
    stage_completed,
)
from agent_controller.guards import (
    GuardLimits,
    GuardVerdict,
    LoopGuard,
    check_counters,
    failure_fingerprint,
)
from agent_controller.human import (
    AnswerRejected,
    answer_question,
    complete_blockers,
)
from agent_controller.git_checkpoint import (
    DirtyWorkingTreeError,
    GitCheckpointError,
    GitCheckpointManager,
)
from agent_controller.graph import wired_handlers
from agent_controller.impact import (
    ImpactAnalyzer,
    ImpactResult,
    default_impact_analyzer,
    merge_impacts,
    validate_impact_result,
)
from agent_controller.migrations import LATEST_VERSION, SchemaError
from agent_controller.models import (
    DEFAULT_REVIEW_LEVELS,
    ArtifactKind,
    ArtifactState,
    ArtifactStatus,
    AcceptanceContract,
    ContractStatus,
    DocumentStage,
    Event,
    Phase,
    Question,
    QuestionStatus,
    RecoveryAttempt,
    ReviewLevel,
    Role,
    RunState,
    RunStatus,
    State,
    TaskType,
    Transition,
    Worker,
)
from agent_controller.qanda import QandaFile, render_qanda
from agent_controller.router import classify_task_type, skipped_stages_for_task_type, stages_for_task_type
from agent_controller.transitions import (
    RESUME,
    TRANSITIONS,
    MissingReturnStateError,
    UnknownTransitionError,
    allowed_events,
    next_state,
)
from agent_controller.worker import (
    WorkerAdapter,
    WorkerRequest,
    WorkerResult,
    WorkerRouter,
    phase_handlers_for_stages,
    phase_handlers_from_worker,
)

__all__ = [
    "DEFAULT_REVIEW_LEVELS",
    "RESUME",
    "STAGE_TRANSITIONS",
    "LATEST_VERSION",
    "TRANSITIONS",
    "AnswerRejected",
    "ArtifactKind",
    "ArtifactState",
    "ArtifactStatus",
    "AcceptanceContract",
    "ContractStatus",
    "ClaudeCodeWorker",
    "AgyCliWorker",
    "DEFAULT_CAPABILITIES",
    "WorkerCapability",
    "capability_for",
    "classify_worker_error",
    "satisfies",
    "RecoveryAttempt",
    "TaskType",
    "classify_task_type",
    "stages_for_task_type",
    "skipped_stages_for_task_type",
    "design_stages_for_task_type",
    "mark_fast_path_skips",
    "CompleteBlocker",
    "CompleteBlockerCode",
    "CompleteCheckResult",
    "CompleteGate",
    "CompleteGateError",
    "ensure_todo_contracts",
    "verify_contract",
    "verify_contracts",
    "CodexCliWorker",
    "GrokCliWorker",
    "DocumentStage",
    "DocumentStageConfig",
    "DirtyWorkingTreeError",
    "Event",
    "GuardLimits",
    "GitCheckpointError",
    "GitCheckpointManager",
    "GuardVerdict",
    "ImpactAnalyzer",
    "ImpactResult",
    "LoopGuard",
    "MissingReturnStateError",
    "Phase",
    "QandaFile",
    "Question",
    "QuestionStatus",
    "ReviewLevel",
    "Role",
    "RunState",
    "RunStatus",
    "SchemaError",
    "State",
    "Transition",
    "UnknownTransitionError",
    "Worker",
    "WorkerAdapter",
    "WorkerRequest",
    "WorkerResult",
    "WorkerRouter",
    "wired_handlers",
    "allowed_events",
    "answer_question",
    "check_counters",
    "complete_blockers",
    "default_design_stages",
    "default_impact_analyzer",
    "design_artifact_statuses",
    "failure_fingerprint",
    "invalidate_from",
    "merge_impacts",
    "next_phase",
    "next_state",
    "phase_handlers_from_worker",
    "phase_handlers_for_stages",
    "render_qanda",
    "run_design",
    "run_document_stage",
    "stage_completed",
    "validate_impact_result",
]
