"""Agent Controller: deterministic state machine driving exchangeable AI workers."""

from agent_controller.design import (
    default_design_stages,
    design_artifact_statuses,
    invalidate_from,
    run_design,
)
from agent_controller.document_stage import (
    STAGE_TRANSITIONS,
    DocumentStageConfig,
    next_phase,
    run_document_stage,
    stage_completed,
)
from agent_controller.guards import (
    GuardLimits,
    GuardVerdict,
    LoopGuard,
    check_counters,
    failure_fingerprint,
)
from agent_controller.models import (
    DEFAULT_REVIEW_LEVELS,
    ArtifactKind,
    ArtifactState,
    ArtifactStatus,
    DocumentStage,
    Event,
    Phase,
    ReviewLevel,
    Role,
    RunState,
    RunStatus,
    State,
    Transition,
    Worker,
)
from agent_controller.transitions import (
    RESUME,
    TRANSITIONS,
    MissingReturnStateError,
    UnknownTransitionError,
    allowed_events,
    next_state,
)

__all__ = [
    "DEFAULT_REVIEW_LEVELS",
    "RESUME",
    "STAGE_TRANSITIONS",
    "TRANSITIONS",
    "ArtifactKind",
    "ArtifactState",
    "ArtifactStatus",
    "DocumentStage",
    "DocumentStageConfig",
    "Event",
    "GuardLimits",
    "GuardVerdict",
    "LoopGuard",
    "MissingReturnStateError",
    "Phase",
    "ReviewLevel",
    "Role",
    "RunState",
    "RunStatus",
    "State",
    "Transition",
    "UnknownTransitionError",
    "Worker",
    "allowed_events",
    "check_counters",
    "default_design_stages",
    "design_artifact_statuses",
    "failure_fingerprint",
    "invalidate_from",
    "next_phase",
    "next_state",
    "run_design",
    "run_document_stage",
    "stage_completed",
]
